name: cypress

on:
  push:
    branches: [ "master" ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NPM dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Start Application
        run: npm start
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
